import { useState } from "react";
import { CA, CO } from "../assets/images/SVG";
const EnglishText = () => {
    return (
        <div className="justify-self-end">
            <p id="purpouse"><strong>Purpouse</strong></p>
            <div>
                <p className="my-2">
                    The purpose of this policy is to establish criteria to ensure respect for personal, family, image and good name of the holders of the information, in compliance with the provisions of article 15 of the Political Constitution, Law 1266 of 2008, Statutory Law 1581 of 2012, Decree Regulation 1377 of 2013 and other provisions that add or amend them.
                    Consequently, all actions of ECONNABIS S.A.S. in matters of Habeas Data will be governed by the principles of legality, purpose, freedom, veracity or quality, transparency, access and restricted circulation, security and confidentiality.
                </p>
            </div>

            <p id="scope" className="my-4"><strong>Scope</strong></p>
            <p className="my-2">This Policy is of mandatory compliance for employees, contractors and third parties, who are in charge of processing personal data, and applies to all personal information recorded in the databases of ECONNABIS S.A.S.</p>

            <p id="definitions" className="my-4"><strong>Definitions</strong></p>
            <div className="my-2">
                In accordance with the current regulations and for the purposes of this Policy, the following means:
                <p><strong>Holder: </strong>Natural person whose personal data are processed.</p>

                <p><strong>Treatment: </strong>Any operation or set of operations on personal data, such as collection, storage, use, circulation, or deletion.</p>

                <p><strong>Personal Data: </strong>Any information linked to or that may be associated with one or more specific or determinable natural persons.</p>

                <p><strong>Sensitive data: </strong>Sensitive data means data that affect the privacy of the holder or whose misuse may lead to discrimination, such as those that reveal racial or ethnic origin, political orientation, religious or philosophical beliefs, membership of trade unions, social organizations, human rights organizations or that promotes the interests of any political party or that guarantee the rights and guarantees of opposition political parties , as well as data on health, sex life, and biometric data.</p>

                <p><strong>Public fact: </strong>This is data that is not semi private, private or sensitive. Public data are considered, inter alia, data relating to the marital status of persons, their profession or occupation and their status as a trader or public servant. By their nature, public data may be contained, among others, in public registers, public documents, gazettes and official gazettes and duly enforceable court judgments that are not subject to reservation.</p>

                <p><strong>Database: </strong>Organized set of personal data that is object of treatment.</p>

                <p><strong>Authorization: </strong>Prior, express, and informed consent of the holder to carry out the processing of personal data.</p>

                <p><strong>Privacy Notice: </strong>Verbal or written communication generated by the responsible, addressed to the holder for the processing of his personal data, through which he is informed about the existence of the information processing policies that will be applicable to him, the way of accessing them and the purposes of the processing that is intended to be given to personal data.</p>

                <p><strong>Responsible for the treatment: </strong>Natural or legal person, public or private, who by herself or in partnership with others, decides on the database and/or the treatment of the data.</p>

                <p><strong>Entrusted of treatment: </strong>Natural or legal person, public or private, who by himself or in association with others, performs the processing of personal data on behalf of the person responsible for the treatment.</p>

                <p><strong>Transfer: </strong>The transfer of data takes place when the responsible and/or the entrusted of personal data treatment, located in Colombia, sends the information or personal data to a receiver, which in turn is responsible of the treatment and is located inside or outside the country.</p>

                <p><strong>Transmission: </strong>processing of personal data involving the communication of the same within or outside the territory of the Republic of Colombia when it is intended to carry out a processing by the person responsible on behalf.</p>
            </div>

            <p id="data-controller" className="my-4"><strong>Data Controller</strong></p>
            <div className="my-2">
                ECONNABIS S.A.S, acting as responsible for the processing of personal data, is a commercial company, legally constituted by a private document of March 8, 2016, identified with NIT. 900949684-6, whose social purpose is the collection and possession of cannabis seeds and the development of agro-industrial activities related to the exploitation of the cannabis plant for medicinal and scientific purposes.

                <p><strong>Main address: </strong>Predio Rural El Cacho Viejo, Vereda Checua, Nemocón, Cundinamarca Republic of Colombia. </p>

                <p><strong>Website: </strong>www.plena-global.com </p>

                <p><strong>Phone: </strong>7943135. </p>
            </div>

            <p id="treatment-and-its-purposes" className="my-4"><strong>Treatment and its Purposes</strong></p>
            <div className="my-2">
                In the development of its contractual and commercial activities ECONNABIS S.A.S. collects, stores, uses, circulates, updates, transmits, transfers, and deletes personal data of the holder for the purpose of:

                <p><strong>a)</strong> To comply with the obligations undertaken by ECONNABIS S.A.S. arising from the employment relationship with the information holder, such as payment of wages, social benefits, contracting life insurance and medical expenses, attending procedures typical of the social security system and other remuneration enshrined in the employment contract or as provided by the law.</p>

                <p><strong>b)</strong> Develop personnel recruitment and linking processes in accordance with internal policies.</p>

                <p><strong>c)</strong> Control the entry and exit of staff to record compliance with the working day.</p>

                <p><strong>d)</strong> Provide the services offered by ECONNABIS S.AS. in accordance with the contract, report services and products and maintain contact with customers.</p>

                <p><strong>e)</strong> Notify family members in case of emergency and ensure the safety of employees, visitors, property and facilities of ECONNABIS S.A.S. by video surveillance.</p>

                <p><strong>f)</strong> Contact the holder for him sent extracts, statements, or invoices in relation to the obligations arising from contracts concluded with suppliers, as well as to follow up on his management and report on future projects of ECONNABIS S.A.S.</p>

                <p><strong>g)</strong> View financial information, credit history and reports that are stored in databases of risk centers.</p>


                <p><strong>h)</strong> Transmission and/or transfer of personal data outside the country to the parent company or to third parties with whom ECONNABIS S.A.S. has a commercial and legal relationship.</p>

                <p><strong>i)</strong> Advance internal or external audit processes.</p>

                <p><strong>j)</strong> Offer corporate welfare programs and plan business activities, for the Holder and its beneficiaries.</p>

                <p><strong>k)</strong> Business development with customers and suppliers.</p>

                <p><strong>l)</strong> Use of video surveillance systems and implementation of security measures.</p>

                <p><strong>m)</strong> The others indicated in the authorization granted by the data subject or described in the privacy notice, as the case may be.</p>

                The processing of personal data mentioned will be done only and exclusively when ECONNABIS S.A.S has obtained the voluntary, prior and express consent of the holder by any means that may be subject to further consultation, except in the cases established in article 10 of law 1581 of 2012, in which authorization is not necessary. If the processing of data of a nature of minors is required, ECONNABIS S.A.S. will ensure the proper use of them and ensure that the treatment responds and respects the best interests of children and adolescents and ensures respect for their fundamental rights.
            </div>

            <p id="holders-rights" className="my-4"><strong>Holders Rights</strong></p>
            <div className="my-2">
                In accordance with the provisions of Law 1581 of 2012, holders of personal data who rest in the database of ECONNABIS S.A.S. have the right to:

                <p><strong>a)</strong> Know, update and rectify their personal data against partial, inaccurate, incomplete, fractional data that mislead, or those whose processing is expressly prohibited or has not been authorized.</p>

                <p><strong>b)</strong> Request proof of authorization granted to the Responsible for the treatment except where expressly exempted as a requirement for the Treatment, in accordance with the provisions of article 10 of this law 1581 of 2012.</p>

                <p><strong>c)</strong> Right to be informed about their use of personal data.</p>

                <p><strong>d)</strong> File complaints with the Superintendence of Industry and Commerce for violations of the provisions of the Law and the other rules that modify, add or supplement it.</p>

                <p><strong>e)</strong> Revoke the authorization and/or request the deletion of the data when the principles, rights and constitutional and legal guarantees are not respected.</p>

                <p><strong>f)</strong> Refrain from answering questions about sensitive data. Responses on sensitive data or data on girls, boys and adolescents will be optional.</p>

                <p><strong>g)</strong> Free access to their personal data that has been processed free of charge.</p>
                <p><strong>Procedures for the Exercise of Habeas Data Law</strong></p>
            </div>

            <p id="procedure-for-access-and-consultation" className="my-4"><strong>Procedure for access and consultation:</strong></p>
            <div className="my-2">
                The holder, or his successor, may consult the information that rests in any database of ECONNABIS S.A.S. by written request addressed to the email
                comunicacionesexternas@plena.global

                ECONNABIS S.A.S. will attend your inquiries within a maximum of ten (10) working days from the date of receipt of the same.

                Where it is not possible to attend the consultation within that term, the interested party will be informed, expressing the reasons for the delay and indicating the date on which his consultation will be attended, which in no case may exceed five (5) working days following the expiration of the first term.

                Once the consultation process has been completed, the holder or successor may raise a complaint with the Superintendence of Industry and Commerce.

                Procedure for claims and request corrections, updates, deletion or revocation.

                The holder, or its successors, who considers that the information contained in a database of ECONNABIS S.A.S. should be corrected, updated or deleted, or when he notices the alleged breach of any of the duties contained in the law, may file a claim and take into account the following:

                <p><strong>1)</strong> You should contact the email comunicacionesexternas@plena.global</p>

                <p><strong>2)</strong> The holder shall identify himself fully, describe the facts giving rise to the claim and the reasons for the alleged non compliance, indicate the address and documents to be enforced.</p>

                <p><strong>3)</strong> If the claim is incomplete, the data subject will be required within five (5) days of receipt of the claim to remedy the failures. After two (2) months from the date of the request, without the applicant submitting the required information, it will be understood that he has given up the claim. In the event that the person who receives the claim is not competent to resolve it, he/she will transfer to the appropriate person within a maximum period of two (2) working days and inform the interested party of the situation.</p>

                <p><strong>4)</strong> Once the complete claim is received, a legend that says, "claim in process" and the reason for it will be included in the database, in a term of no more than two (2) business days. Such legend must be maintained until the claim is decided.</p>

                <p><strong>5)</strong> The maximum term to meet the claim shall be fifteen (15) working days from the day following the date of receipt. Where it is not possible to address the claim within that term, the interested party shall be informed of the reasons for the delay and the date on which his claim will be addressed, which in no case may exceed eight (8) working days following the expiration of the first term.</p>

                <p><strong>6)</strong> Once the claim process has been exhausted, the holder or successor can file a complaint with the Superintendence of Industry and Commerce.</p>
            </div>


            <p id="area-responsible-for-the-attenttion-of-requests-consultation-and-claims" className="my-4"><strong>Area Responsible for the Attenttion of Requests, Consultation and Claims</strong></p>
            <div className="my-2">
                The Legal area is the unit that is responsible for processing the requests of the holder, or of the person exercising his representation, to make effective his rights, which, may be presented by physical or digital means through the following channels of attention:

                To the Email: comunicacionesexternas@plena.global

                To the telephone line: 7943135
            </div>

            <p id="security-measures" className="my-4"><strong>Security Measures</strong></p>
            <div className="my-2">
                In development of the principle of security, ECONNABIS S.A.S. ensures the preservation of information with the adoption of physical and technical security conditions, necessary to prevent its adulteration, loss, consultation, use or unauthorized or fraudulent access.

                The authorized personnel to access the databases managed by ECONNABIS S.A.S. should implement internal policies and protocols to ensure information security.
            </div>

            <p id="validity" className="my-4"><strong>Validity</strong></p>
            <div className="my-2">
                This Policy for the Processing of Personal Data applies from January 1, two thousand nineteen (2021).

                The databases in which the personal data will be recorded will be valid equal to the time the information is maintained and used for the purposes described in this policy.


                Once these purposes are fulfilled and if there is no legal or contractual duty to retain your information, the data will be deleted from our databases.

                The period of time that the information will remain in the database for video surveillance purposes will be 30 days as the maximum limit.
            </div>
        </div>
    );
}
const SpanishText = () => {
    return (
        <div className="justify-self-end">

            <p id="objetivo" className="my-4"><strong>Objetivo</strong></p>
            <div className="my-2">
                La presente política tiene como propósito establecer criterios para garantizar el respecto a la intimidad personal, familiar, a la imagen y al buen nombre de los titulares de la información, en cumplimiento a lo establecido en el artículo 15 de la Constitución Política, la Ley 1266 de 2008, la Ley Estatutaria 1581 de 2012, el Decreto Reglamento 1377 de 2013 y demás disposiciones que las adicionen o modifiquen.

                En consecuencia, todas las actuaciones de ECONNABIS S.A.S. en materia de Habeas Data se regirán bajo los principios de legalidad, finalidad, libertad, veracidad o calidad, transparencia, acceso y circulación restringida, seguridad y confidencialidad.
            </div>

            <p id="alcance" className="my-4" ><strong>Alcance</strong></p>
            <div className="my-2">
                Esta Política es de cumplimiento obligatorio para empleados, contratistas y terceros, quienes actúen en calidad de encargados del tratamiento, y aplica para toda la información personal registrada en las bases de datos de ECONNABIS S.A.S.
            </div>

            <p id="definiciones" className="my-4" ><strong>Definiciones</strong></p>
            <div className="my-2">
                En concordancia con la normatividad vigente y para efectos de la presente Política, se entiende por:

                <p><strong>Titular:</strong> Persona natural cuyos datos personales sean objeto de tratamiento.</p>

                <p><strong>Tratamiento:</strong> Cualquier operación o conjunto de operaciones sobre datos personales, tales como la recolección, almacenamiento, uso, circulación o supresión.</p>

                <p><strong>Dato personal:</strong> Cualquier información vinculada o que pueda asociarse a una o varias personas naturales determinadas o determinables.</p>

                <p><strong>Datos sensibles:</strong> Se entiende por datos sensibles aquellos que afectan la intimidad del titular o cuyo uso indebido puede generar su discriminación, tales como aquellos que revelen el origen racial o étnico, la orientación política, las convicciones religiosas o filosóficas, la pertenencia a sindicatos, organizaciones sociales, de derechos humanos o que promueva intereses de cualquier partido político o que garanticen los derechos de partidos políticos de oposición, así como los datos relativos a la salud, a la vida sexual, y los datos biométricos.</p>

                <p><strong>Dato público:</strong> Es el dato que no sea semiprivado, privado o sensible. Son considerados datos públicos, entre otros, los datos relativos al estado civil de las personas, a su profesión u oficio y a su calidad de comerciante o de servidor público. Por su naturaleza, los datos públicos pueden estar contenidos, entre otros, en registros públicos, documentos públicos, gacetas y boletines oficiales y sentencias judiciales debidamente ejecutoriadas que no estén sometidas a reserva.</p>

                <p><strong>Base de Datos:</strong> Conjunto organizado de datos personales que sea objeto de Tratamiento.</p>

                <p><strong>Autorización:</strong> Consentimiento previo, expreso e informado del titular para llevar a cabo el tratamiento de datos personales.</p>

                <p><strong>Aviso de privacidad:</strong> Comunicación verbal o escrita generada por el responsable, dirigida al titular para el tratamiento de sus datos personales, mediante la cual se le informa acerca de la existencia de las políticas de tratamiento de información que le serán aplicables, la forma de acceder a las mismas y las finalidades del tratamiento que se pretende dar a los datos personales.</p>

                <p><strong>Responsable del Tratamiento:</strong> Persona natural o jurídica, pública o privada, que por sí misma o en asocio con otros, decida sobre la base de datos y/o el tratamiento de los datos.</p>

                <p><strong>Encargado del Tratamiento:</strong> Persona natural o jurídica, pública o privada, que por sí misma o en asocio con otros, realice el tratamiento de datos personales por cuenta del responsable del tratamiento.</p>

                <p><strong>Transferencia:</strong> La transferencia de datos tiene lugar cuando el responsable y/o encargado del tratamiento de datos personales, ubicado en Colombia, envía la información o los datos personales a un receptor, que a su vez es responsable del tratamiento y se encuentra dentro o fuera del país.</p>

                <p><strong>Transmisión:</strong> tratamiento de datos personales que implica la comunicación de los mismos dentro o fuera del territorio de la República de Colombia cuando tenga por objeto la realización de un tratamiento por el encargado por cuenta del responsable.</p>
            </div>

            <p id="responsable-del-tratamiento-de-la-informacion" className="my-4" ><strong>Responsable del Tratamiento de la Información</strong></p>
            <div className="my-2">
                ECONNABIS S.A.S, actúa en calidad de responsable del tratamiento de los datos personales, es una sociedad comercial, legalmente constituida por documento privado del 8 de marzo de 2016, identificada con el NIT. 900949684-6, cuyo objeto social es la obtención y posesión de semillas de cannabis y el desarrollo de actividades agroindustriales relacionadas con la explotación de la planta del cannabis con fines medicinales y científicos.

                <p><strong>Domicilio principal: </strong>Predio Rural El Cacho Viejo, Vereda Checua, Nemocón, Cundinamarca, Republica de Colombia.</p>

                <p><strong>Página web: </strong>www.plena-global.com</p>

                <p><strong>Teléfono: </strong>7943135.</p>
            </div>


            <p id="tratamiento-y-sus-finalidades" className="my-4" ><strong>Tratamiento y sus Finalidades</strong></p>
            <div className="my-2">
                En desarrollo de sus actividades contractuales y comerciales ECONNABIS S.A.S. recolecta, almacena, usa, circula, actualiza, transmite, transfiere y suprime datos personales del titular con la finalidad de:

                <p><strong>a)</strong> Dar cumplimiento a las obligaciones contraídas por ECONNABIS S.A.S. derivadas de la relación laboral con el titular de la información, tales como pago de salarios, prestaciones sociales, contratación de seguros de vida y gastos médicos, atender tramites propios del sistema de seguridad social y demás retribuciones consagradas en el contrato de trabajo o según lo disponga la ley.</p>

                <p><strong>b)</strong> Desarrollar procesos de selección y vinculación de personal de conformidad con las políticas internas.</p>

                <p><strong>c)</strong> Controlar el ingreso y salida del personal para registrar el cumplimiento de la jornada laboral.</p>

                <p><strong>d)</strong> Prestar los servicios ofrecidos por ECONNABIS S.AS. de acuerdo con el contrato, informar servicios y productos y mantener contacto con clientes.</p>

                <p><strong>e)</strong> Notificar a familiares en caso de emergencia y garantizar la seguridad de empleados, visitantes y bienes e instalaciones de ECONNABIS S.A.S. mediante video vigilancia.</p>

                <p><strong>f)</strong> Contactar al titular para él envió de extractos, estados de cuenta o facturas en relación con las obligaciones derivadas de contratos celebrados con proveedores, así como para hacer seguimientos a su gestión e informar sobre futuros proyectos de ECONNABIS S.A.S.</p>

                <p><strong>g)</strong> Consultar información financiera, historial crediticio y reportes que sobre los titulares se encuentre almacenada en bases de datos de centrales de riesgo.</p>

                <p><strong>h)</strong> Transmisión y/o transferencia de datos personales fuera del país a la casa matriz o a terceros con los cuales ECONNABIS S.A.S. tenga una relación comercial y legal.</p>

                <p><strong>i)</strong> Adelantar procesos de auditoría interna o externa.</p>

                <p><strong>j)</strong> Ofrecer programas de bienestar corporativo y planificar actividades empresariales, para el Titular y sus beneficiarios.</p>

                <p><strong>k)</strong> Desarrollo de negocios con clientes y proveedores.</p>

                <p><strong>l)</strong> Uso de sistemas de videovigilancia e implementación de medidas de seguridad.</p>

                <p><strong>m)</strong> Las demás indicadas en la autorización otorgada por el titular del dato o descritos en el aviso de privacidad, según sea el caso.</p>

                El tratamiento de datos personales mencionado se hará única y exclusivamente cuando ECONNABIS S.A.S haya obtenido el consentimiento voluntario, previo y expreso del titular por cualquier medio que pueda ser objeto de consulta posterior, salvo los casos establecidos en el artículo 10 de la ley 1581 de 2012, en los que no es necesaria la autorización. De requerirse el tratamiento de datos de naturaleza de menores de edad, ECONNABIS S.A.S., velara por el uso adecuado de los mismos y garantizará que el tratamiento responda y respete el interés superior de los niños, niñas y adolescentes y asegure el respeto de sus derechos fundamentales.
            </div>

            <p id="derechos-de-los-titulares" className="my-4"><strong>Derechos de los Titulares</strong></p>
            <div className="my-2">
                <p><strong>a)</strong> Conocer, actualizar y rectificar sus datos personales frente a datos parciales, inexactos, incompletos, fraccionados, que induzcan a error, o aquellos cuyo tratamiento esté expresamente prohibido o no haya sido autorizado.</p>
                De conformidad con lo establecido en la Ley 1581 de 2012, los titulares de datos personales que reposen en la base de datos de ECONNABIS S.A.S. tienen derecho a:

                <p><strong>b)</strong> Solicitar prueba de la autorización otorgada al responsable del tratamiento salvo cuando expresamente se exceptúe como requisito para el tratamiento, de conformidad con lo previsto en el artículo 10 de la presente ley 1581 de 2012.</p>

                <p><strong>c)</strong> Derecho a ser informado respecto del uso que le ha dado a sus datos personales.</p>

                <p><strong>d)</strong> Presentar ante la Superintendencia de Industria y Comercio quejas por infracciones a lo dispuesto en la ley y las demás normas que la modifiquen, adicionen o complementen.</p>

                <p><strong>e)</strong> Revocar la autorización y/o solicitar la supresión del dato cuando en el tratamiento no se respeten los principios, derechos y garantías constitucionales y legales.</p>

                <p><strong>f)</strong> Abstenerse de responder a las preguntas sobre datos sensibles. tendrá carácter facultativo las respuestas que versen sobre datos sensibles o sobre datos de las niñas, niños y adolescentes.</p>

                <p><strong>g)</strong> Acceder en forma gratuita a sus datos personales que hayan sido objeto de Tratamiento.</p>
            </div>

            <p id="procedimientos-para-el-ejercicio-del-derecho-de-habeas-data" className="my-4"><strong>Procedimientos para el Ejercicio del Derecho de Habeas Data</strong></p>
            <div className="my-2">
                <p><strong>Procedimiento de acceso y consulta:</strong></p>
                El titular, o su causahabiente, podrá consultar la información que repose en cualquier base de datos de ECONNABIS S.A.S. mediante solicitud escrita dirigida al correo electrónico comunicacionesexternas@plena.global

                ECONNABIS S.A.S., atenderá sus consultas en un término máximo de diez (10) días hábiles contados a partir de la fecha de recibo de la misma.

                Cuando no fuere posible atender la consulta dentro de dicho término, se informará al interesado, expresando los motivos de la demora y señalando la fecha en que se atenderá su consulta, la cual en ningún caso podrá superar los cinco (5) días hábiles siguientes al vencimiento del primer término.

                Una vez agotado el trámite de consulta, el titular o causahabiente podrá elevar queja ante la Superintendencia de Industria y Comercio.

                Procedimiento de reclamos y solicitud de correcciones, actualizaciones, supresión o revocatoria.

                El titular, o sus causahabientes, que considere que la información contenida en una base de datos de ECONNABIS S.A.S. debe ser objeto de corrección, actualización o supresión, o cuando advierta el presunto incumplimiento de cualquiera de los deberes contenidos en la ley, podrá presentar un reclamo y tener en cuenta lo siguiente:

                <p><strong>1)</strong> Deberá dirigirse al correo electrónico comunicacionesexternas@plena.global</p>

                <p><strong>2)</strong> El titular deberá identificarse plenamente, describir los hechos que dan lugar al reclamo y las razones del presunto incumplimiento, indicar la dirección y los documentos que se quieran hacer valer.</p>

                <p><strong>3)</strong> Si el reclamo resulta incompleto, se requerirá al interesado dentro de los cinco (5) días siguientes a la recepción del reclamo para que subsane las fallas. Transcurridos dos (2) meses desde la fecha del requerimiento, sin que el solicitante presente la información requerida, se entenderá que ha desistido del reclamo. En caso de que quien reciba el reclamo no sea competente para resolverlo, dará traslado a quien corresponda en un término máximo de dos (2) días hábiles e informará de la situación al interesado.</p>

                <p><strong>4)</strong> Una vez recibido el reclamo completo, se incluirá en la base de datos una leyenda que diga “reclamo en trámite” y el motivo del mismo, en un término no mayor a dos (2) días hábiles. Dicha leyenda deberá mantenerse hasta que el reclamo sea decidido.</p>

                <p><strong>5)</strong> El término máximo para atender el reclamo será de quince (15) días hábiles contados a partir del día siguiente a la fecha de su recibo. Cuando no fuere posible atender el reclamo dentro de dicho término, se informará al interesado los motivos de la demora y la fecha en que se atenderá su reclamo, la cual en ningún caso podrá superar los ocho (8) días hábiles siguientes al vencimiento del primer término.</p>

                <p><strong>6)</strong> Una vez agotado el trámite de reclamo, el titular o causahabiente podrá elevar queja ante la Superintendencia de Industria y Comercio</p>
            </div>


            <p id="area-responsable-de-la-atención-de-peticiones-consultas-y-reclamos" className="my-4"><strong>Área Responsable de la Atención de Peticiones, Consultas y Reclamos</strong></p>
            <div className="my-2">
                El área Jurídica es la dependencia que tiene a cargo dar trámite a las solicitudes del titular, o de quien ejerza su representación, para hacer efectivos sus derechos, las cuales, podrán ser presentadas por medio físico o digital a través de los siguientes canales de atención:

                Al Correo electrónico: comunicacionesexternas@plena.global

                A la línea telefónica: 7943135
            </div>


            <p id="medidas-de-seguridad" className="my-4"><strong>Medidas de Seguridad</strong></p>
            <div className="my-2">
                En desarrollo del principio de seguridad, ECONNABIS S.A.S. vela por la conservación de la información con la adopción de condiciones de seguridad físicas y técnicas, necesarias para impedir su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento.

                El personal autorizado para tener acceso a las bases de datos que administra ECONNABIS S.A.S. ejecutará las políticas y protocolos internos a fin de garantizar la seguridad de la información.
            </div>

            <p id="vigencia" className="my-4"><strong>Vigencia</strong></p>
            <div className="my-2">
                La presente Política para el Tratamiento de Datos Personales rige a partir del 1 de enero dos mil diecinueve (2021).

                Las bases de datos en las que se registrarán los datos personales tendrán una vigencia igual al tiempo en que se mantenga y utilice la información para las finalidades descritas en esta política.

                Una vez se cumplan esas finalidades y siempre que no exista un deber legal o contractual de conservar su información, los datos serán eliminados de nuestras bases de datos.

                El periodo de tiempo que permanecerá la información en la base de datos con fines de video vigilancia será de 30 días como límite máximo.
            </div>
        </div>
    );
}

const InformedConsentLaw1581 = () => {
    const [languague, setLanguague] = useState("Español")
    return (
        <>
            <div className="grid grid-cols-3 h-[80vh] bg-white">
                <div className="overflow-y-scroll col-span-2 mx-5">
                    {languague === "Español" ? <SpanishText /> : <EnglishText />}
                </div>
                <div className="lg:w-[168px] border-black border-l-2 justify-self-end">
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#objetivo">
                                Objetivo
                            </a>
                            :
                            <a href="#purpouse">
                                Purpouse
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#alcance">
                                Alcance
                            </a>
                            :
                            <a href="#scope">
                                Scope
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#definiciones">
                                Definiciones
                            </a>
                            :
                            <a href="#definitions">
                                Definitions
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#responsable-del-tratamiento-de-la-informacion">
                                Responsable del tratamiento de la información
                            </a>
                            :
                            <a href="#data-controller">
                                Data Controller
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#tratamiento-y-sus-finalidades ">
                                Tratamiento y sus finalidades
                            </a>
                            :
                            <a href="#treatment-and-its-purposes">
                                Treatment and its purposes
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#derechos-de-los-titulares">
                                Derechos de los titulares
                            </a>
                            :
                            <a href="#holders-rights">
                                Holders rights
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#procedimientos-para-el-ejercicio-del-derecho-de-habeas-data">
                                Procedimientos para el ejercicio del derecho de habeas data
                            </a>
                            :
                            <a href="#procedure-for-access-and-consultation">
                                Procedures for the exercise of habeas data law
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#area-responsable-de-la-atención-de-peticiones-consultas-y-reclamos">
                                Área responsable de la atención de peticiones, consultas y reclamos
                            </a>
                            :
                            <a href="#area-responsible-for-the-attenttion-of-requests-consultation-and-claims">
                                Area responsible for the attention of requests, consultation and claims
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a href="#medidas-de-seguridad">
                                Medidas de seguridad
                            </a>
                            :
                            <a href="#security-measures">
                                Security measures
                            </a>
                        }
                    </p>
                    <p className="font-arial text-[12px] mx-2 underline underline-offset-2 mb-3">
                        {languague === "Español"
                            ?
                            <a
                                href="#vigencia" >
                                Vigencia
                            </a>
                            :
                            <a href="#validity">
                                Validity
                            </a>
                        }
                    </p>
                    {languague === "Español"
                        ?
                        <>
                            <button className="opacity-50 mx-2" onClick={() => setLanguague("Español")}>
                                <CO />
                            </button>
                            <button
                                onClick={() => setLanguague("English")}
                            >
                                <CA />
                            </button>
                        </>
                        :
                        <>
                            <button className="mx-2" onClick={() => setLanguague("Español")}>
                                <CO />
                            </button>
                            <button
                                className="opacity-50 "
                                onClick={() => setLanguague("English")}
                            >
                                <CA />
                            </button>
                        </>
                    }

                </div>
            </div >
        </>
    )
}

export { EnglishText, SpanishText, InformedConsentLaw1581 };