"""20220301_0804

Revision ID: 06875d5f797b
Revises: fc9f4d7266be
Create Date: 2023-03-01 08:04:04.175936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06875d5f797b'
down_revision = 'fc9f4d7266be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employment_relationship', sa.Column('type_of_charge', sa.String(length=50), nullable=False))
    op.alter_column('tbl_employment_relationship', 'immediate_boss',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tbl_employment_relationship', 'manager',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['immediate_boss'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.alter_column('tbl_employment_relationship', 'manager',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tbl_employment_relationship', 'immediate_boss',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('tbl_employment_relationship', 'type_of_charge')
    # ### end Alembic commands ###
