"""20221203_1927

Revision ID: 08eb8c0d780d
Revises: 71241c5516a0
Create Date: 2022-12-03 19:31:17.500834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08eb8c0d780d'
down_revision = '71241c5516a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_employment_relationship_ibfk_2', 'tbl_employment_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_type_relationship', ['ccn_type_affiliation'], ['ccn_type_relationship'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.create_foreign_key('tbl_employment_relationship_ibfk_2', 'tbl_employment_relationship', 'tbl_type_affiliation', ['ccn_type_affiliation'], ['ccn_type_affiliation'])
    # ### end Alembic commands ###
