"""20230510_0846

Revision ID: 0b74c21dae07
Revises: fe51d02dd5a0
Create Date: 2023-05-10 09:00:34.524913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b74c21dae07'
down_revision = 'fe51d02dd5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['immediate_boss'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    # ### end Alembic commands ###
