"""20221221_1400

Revision ID: 0bd99cd726ff
Revises: ace92dca3549
Create Date: 2022-12-21 14:00:57.779330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bd99cd726ff'
down_revision = 'ace92dca3549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_employment_relationship', 'binding_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tbl_employment_relationship', 'time_worked',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('tbl_employment_relationship', 'pending_days_to_enjoy_for_holidays',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('tbl_employment_relationship', 'employee_corporate_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tbl_employment_relationship', 'employee_corporate_cellphone',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_employment_relationship', 'employee_corporate_cellphone',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('tbl_employment_relationship', 'employee_corporate_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tbl_employment_relationship', 'pending_days_to_enjoy_for_holidays',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('tbl_employment_relationship', 'time_worked',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('tbl_employment_relationship', 'binding_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
