"""20221229_1106

Revision ID: 0dc3503823b1
Revises: d0a38a06eea9
Create Date: 2022-12-29 11:06:21.307363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc3503823b1'
down_revision = 'd0a38a06eea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_city', 'tbl_department', ['ccn_department'], ['ccn_department'])
    op.add_column('tbl_employment_relationship', sa.Column('immediate_boss', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employment_relationship', 'immediate_boss')
    op.drop_constraint(None, 'tbl_city', type_='foreignkey')
    # ### end Alembic commands ###
