"""20230623_0707

Revision ID: 19c1aa8c69ee
Revises: 6b23f8431b09
Create Date: 2023-06-23 07:07:39.733079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c1aa8c69ee'
down_revision = '6b23f8431b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employee', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    # ### end Alembic commands ###
