"""20230313_1600

Revision ID: 19cca12d173d
Revises: 16d850ec8be4
Create Date: 2023-03-13 16:00:53.128254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cca12d173d'
down_revision = '16d850ec8be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_administrative_performance_evaluation', sa.Column('overall_score', sa.Integer(), nullable=True))
    op.add_column('tbl_administrative_performance_evaluation', sa.Column('level_value', sa.String(length=50), nullable=True))
    op.add_column('tbl_directive_performance_evaluation', sa.Column('overall_score', sa.Integer(), nullable=True))
    op.add_column('tbl_directive_performance_evaluation', sa.Column('level_value', sa.String(length=50), nullable=True))
    op.add_column('tbl_operative_performance_evaluation', sa.Column('overall_score', sa.Integer(), nullable=True))
    op.add_column('tbl_operative_performance_evaluation', sa.Column('level_value', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_operative_performance_evaluation', 'level_value')
    op.drop_column('tbl_operative_performance_evaluation', 'overall_score')
    op.drop_column('tbl_directive_performance_evaluation', 'level_value')
    op.drop_column('tbl_directive_performance_evaluation', 'overall_score')
    op.drop_column('tbl_administrative_performance_evaluation', 'level_value')
    op.drop_column('tbl_administrative_performance_evaluation', 'overall_score')
    # ### end Alembic commands ###
