"""20221209_1522

Revision ID: 1da3c066b569
Revises: d8c6fcb31267
Create Date: 2022-12-09 15:24:57.166762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1da3c066b569'
down_revision = 'd8c6fcb31267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_schooling_level', ['ccn_schooling_level'], ['ccn_schooling_level'])
    op.drop_column('tbl_family_nucleus', 'scholarship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_family_nucleus', sa.Column('scholarship', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    # ### end Alembic commands ###
