"""test

Revision ID: 225f1312c8f4
Revises: fa6a6ed89b0d
Create Date: 2023-03-29 14:11:42.687379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225f1312c8f4'
down_revision = 'fa6a6ed89b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_RBAC_modules',
    sa.Column('ccn_rbac_module', sa.Integer(), nullable=False),
    sa.Column('rbac_module', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ccn_rbac_module')
    )
    op.create_table('tbl_RBAC',
    sa.Column('ccn_rbac', sa.Integer(), nullable=False),
    sa.Column('ccn_role', sa.Integer(), nullable=True),
    sa.Column('ccn_rbac_module', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_rbac_module'], ['tbl_RBAC_modules.ccn_rbac_module'], ),
    sa.ForeignKeyConstraint(['ccn_role'], ['tbl_roles.ccn_role'], ),
    sa.PrimaryKeyConstraint('ccn_rbac')
    )
    op.create_foreign_key(None, 'tbl_administrative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_directive_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_operative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_operative_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_directive_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_administrative_performance_evaluation', type_='foreignkey')
    op.drop_table('tbl_RBAC')
    op.drop_table('tbl_RBAC_modules')
    # ### end Alembic commands ###
