"""20220228_1234

Revision ID: 234e648f7dcd
Revises: 5f46cf37dc49
Create Date: 2023-02-28 12:34:10.795732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '234e648f7dcd'
down_revision = '5f46cf37dc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employment_relationship', sa.Column('manager', sa.String(length=50), nullable=False))
    op.add_column('tbl_employment_relationship', sa.Column('type_of_charge', sa.String(length=50), nullable=False))
    op.alter_column('tbl_employment_relationship', 'immediate_boss',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['immediate_boss'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.alter_column('tbl_employment_relationship', 'immediate_boss',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('tbl_employment_relationship', 'type_of_charge')
    op.drop_column('tbl_employment_relationship', 'manager')
    # ### end Alembic commands ###
