"""20221201_1732

Revision ID: 26533df28f02
Revises: 486c6e0fb478
Create Date: 2022-12-01 17:33:55.309499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26533df28f02'
down_revision = '486c6e0fb478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_role',
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('process', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ccn_role')
    )
    op.create_table('tbl_work_shift',
    sa.Column('ccn_work_shift', sa.Integer(), nullable=False),
    sa.Column('description_work_shift', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ccn_work_shift')
    )
    op.create_table('tbl_employment_relationship',
    sa.Column('ccn_employment_relationship', sa.Integer(), nullable=False),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('ccn_work_shift', sa.Integer(), nullable=True),
    sa.Column('ccn_binding_date', sa.Date(), nullable=False),
    sa.Column('time_worked', sa.Float(), nullable=False),
    sa.Column('pending_days_to_enjoy_for_holidays', sa.Float(), nullable=False),
    sa.Column('ccn_type_affiliation', sa.Integer(), nullable=True),
    sa.Column('employee_corporate_email', sa.String(length=100), nullable=False),
    sa.Column('employee_corporate_cellphone', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employee.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_type_affiliation'], ['tbl_type_affiliation.ccn_type_affiliation'], ),
    sa.ForeignKeyConstraint(['ccn_work_shift'], ['tbl_work_shift.ccn_work_shift'], ),
    sa.PrimaryKeyConstraint('ccn_employment_relationship')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_employment_relationship')
    op.drop_table('tbl_work_shift')
    op.drop_table('tbl_role')
    # ### end Alembic commands ###
