"""20230804_0920

Revision ID: 31ddfdae1590
Revises: 44e71f423cd1
Create Date: 2023-08-04 09:20:42.975279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ddfdae1590'
down_revision = '44e71f423cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_demographic_data', sa.Column('birth_country', sa.Integer(), nullable=True))
    op.add_column('tbl_demographic_data', sa.Column('country_residence', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_country', ['country_residence'], ['ccn_country'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_country', ['birth_country'], ['ccn_country'])
    op.add_column('tbl_sociodemographic_data', sa.Column('how_many_people_in_change', sa.Integer(), nullable=False))
    op.add_column('tbl_sociodemographic_data', sa.Column('neighborhood', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_sociodemographic_data', 'neighborhood')
    op.drop_column('tbl_sociodemographic_data', 'how_many_people_in_change')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_column('tbl_demographic_data', 'country_residence')
    op.drop_column('tbl_demographic_data', 'birth_country')
    # ### end Alembic commands ###
