"""20221222_1106

Revision ID: 3865f5651805
Revises: a9cf40b2d4b6
Create Date: 2022-12-22 11:06:13.303015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3865f5651805'
down_revision = 'a9cf40b2d4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_sociodemographic_data', sa.Column('type_transportation_2', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_sociodemographic_data', 'type_transportation_2')
    # ### end Alembic commands ###
