"""20230804_0803

Revision ID: 3a2aa1ce2a34
Revises: 39abb190d654
Create Date: 2023-08-04 08:03:39.129699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2aa1ce2a34'
down_revision = '39abb190d654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_demographic_data', sa.Column('birth_country', sa.Integer(), nullable=True))
    op.add_column('tbl_demographic_data', sa.Column('country_residence', sa.Integer(), nullable=True))
    op.add_column('tbl_sociodemographic_data', sa.Column('how_many_people_in_change', sa.Integer(), nullable=False))
    op.add_column('tbl_sociodemographic_data', sa.Column('neighborhood', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_sociodemographic_data', 'neighborhood')
    op.drop_column('tbl_sociodemographic_data', 'how_many_people_in_change')
    op.drop_column('tbl_demographic_data', 'country_residence')
    op.drop_column('tbl_demographic_data', 'birth_country')
    # ### end Alembic commands ###
