"""20230626_1128

Revision ID: 3e1317166bbb
Revises: 8858498f00ac
Create Date: 2023-06-28 11:28:49.858181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1317166bbb'
down_revision = '8858498f00ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_demographic_data', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_emergency_contact_details', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_employee', ['number_id_employee'])
    op.create_unique_constraint(None, 'tbl_employment_relationship', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_health_condition', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_sociodemographic_data', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_ss_employee', ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_ss_employee', type_='unique')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='unique')
    op.drop_constraint(None, 'tbl_health_condition', type_='unique')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='unique')
    op.drop_constraint(None, 'tbl_employee', type_='unique')
    op.drop_constraint(None, 'tbl_emergency_contact_details', type_='unique')
    op.drop_constraint(None, 'tbl_demographic_data', type_='unique')
    # ### end Alembic commands ###
