"""20221216_0642

Revision ID: 3edc4d74643b
Revises: a839e6cf779c
Create Date: 2022-12-16 18:42:33.913231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edc4d74643b'
down_revision = 'a839e6cf779c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_work_shift', ['ccn_work_shift'], ['ccn_work_shift'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_type_relationship', ['ccn_type_relationship'], ['ccn_type_relationship'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_roles', ['ccn_role'], ['ccn_role'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    # ### end Alembic commands ###
