"""20221209_0803

Revision ID: 40163005c8f3
Revises: 8f99679925d3
Create Date: 2022-12-09 08:05:07.845028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40163005c8f3'
down_revision = '8f99679925d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    # ### end Alembic commands ###
