"""20230804_0818

Revision ID: 44e71f423cd1
Revises: 3a2aa1ce2a34
Create Date: 2023-08-04 08:18:24.275509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e71f423cd1'
down_revision = '3a2aa1ce2a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_country', ['country_residence'], ['ccn_country'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_country', ['birth_country'], ['ccn_country'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    # ### end Alembic commands ###
