"""first migration

Revision ID: 486c6e0fb478
Revises: 
Create Date: 2022-11-25 08:04:19.925165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486c6e0fb478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_aap',
    sa.Column('ccn_aap', sa.Integer(), nullable=False),
    sa.Column('code_aap', sa.String(length=40), nullable=False),
    sa.Column('nit_aap', sa.String(length=20), nullable=False),
    sa.Column('dig_ver', sa.Integer(), nullable=True),
    sa.Column('description_aap', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_aap')
    )
    op.create_table('tbl_afp',
    sa.Column('ccn_afp', sa.Integer(), nullable=False),
    sa.Column('code_afp', sa.String(length=40), nullable=False),
    sa.Column('nit_afp', sa.String(length=20), nullable=False),
    sa.Column('dig_ver', sa.Integer(), nullable=True),
    sa.Column('description_afp', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_afp')
    )
    op.create_table('tbl_age_range',
    sa.Column('ccn_age_range', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ccn_age_range')
    )
    op.create_table('tbl_arl',
    sa.Column('ccn_arl', sa.Integer(), nullable=False),
    sa.Column('code_arl', sa.String(length=40), nullable=False),
    sa.Column('nit_arl', sa.String(length=20), nullable=False),
    sa.Column('dig_ver', sa.Integer(), nullable=True),
    sa.Column('description_arl', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_arl')
    )
    op.create_table('tbl_auto_perceived_gender',
    sa.Column('ccn_auto_perceived_gender', sa.Integer(), nullable=False),
    sa.Column('auto_perceived_gender', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('ccn_auto_perceived_gender')
    )
    op.create_table('tbl_ccf',
    sa.Column('ccn_ccf', sa.Integer(), nullable=False),
    sa.Column('code_ccf', sa.String(length=40), nullable=False),
    sa.Column('nit_ccf', sa.String(length=20), nullable=False),
    sa.Column('dig_ver', sa.Integer(), nullable=True),
    sa.Column('description_ccf', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_ccf')
    )
    op.create_table('tbl_country',
    sa.Column('ccn_country', sa.Integer(), nullable=False),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('description_country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_country')
    )
    op.create_table('tbl_eps',
    sa.Column('ccn_eps', sa.Integer(), nullable=False),
    sa.Column('code_eps', sa.String(length=40), nullable=True),
    sa.Column('code_sgp_eps', sa.String(length=40), nullable=True),
    sa.Column('nit_eps', sa.String(length=20), nullable=False),
    sa.Column('dig_ver', sa.Integer(), nullable=True),
    sa.Column('description_eps', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_eps')
    )
    op.create_table('tbl_rh',
    sa.Column('ccn_rh', sa.Integer(), nullable=False),
    sa.Column('rh', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('ccn_rh')
    )
    op.create_table('tbl_role',
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('process', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ccn_role')
    )
    op.create_table('tbl_type_affiliation',
    sa.Column('ccn_type_affiliation', sa.Integer(), nullable=False),
    sa.Column('affiliation_code', sa.Integer(), nullable=False),
    sa.Column('description_type_affiliation', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ccn_type_affiliation')
    )
    op.create_table('tbl_type_contributor',
    sa.Column('ccn_type_contributor', sa.Integer(), nullable=False),
    sa.Column('contributor_code', sa.Integer(), nullable=False),
    sa.Column('description_type_contributor', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('ccn_type_contributor')
    )
    op.create_table('tbl_type_id',
    sa.Column('ccn_type_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.String(length=2), nullable=False),
    sa.Column('description_type_id', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ccn_type_id')
    )
    op.create_table('tbl_department',
    sa.Column('ccn_department', sa.Integer(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('descripcion_department', sa.String(length=60), nullable=False),
    sa.Column('ccn_country', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_country'], ['tbl_country.ccn_country'], ),
    sa.PrimaryKeyConstraint('ccn_department')
    )
    op.create_table('tbl_employee',
    sa.Column('ccn_employee', sa.Integer(), nullable=False),
    sa.Column('ccn_type_id', sa.Integer(), nullable=True),
    sa.Column('number_id_employee', sa.Integer(), nullable=False),
    sa.Column('first_name_employee', sa.String(length=30), nullable=False),
    sa.Column('middle_name_employee', sa.String(length=30), nullable=True),
    sa.Column('first_last_name_employee', sa.String(length=30), nullable=False),
    sa.Column('second_last_name_employee', sa.String(length=30), nullable=True),
    sa.Column('full_name_employee', sa.String(length=200), nullable=False),
    sa.Column('date_birth_employee', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.Integer(), nullable=True),
    sa.Column('auto_perceived_gender', sa.Integer(), nullable=True),
    sa.Column('rh', sa.Integer(), nullable=True),
    sa.Column('employee_personal_email', sa.String(length=100), nullable=False),
    sa.Column('employee_personal_cellphone', sa.String(length=40), nullable=False),
    sa.Column('informed_consent_law_1581', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('employee_password', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['age_range'], ['tbl_age_range.ccn_age_range'], ),
    sa.ForeignKeyConstraint(['auto_perceived_gender'], ['tbl_auto_perceived_gender.ccn_auto_perceived_gender'], ),
    sa.ForeignKeyConstraint(['ccn_type_id'], ['tbl_type_id.ccn_type_id'], ),
    sa.ForeignKeyConstraint(['rh'], ['tbl_rh.ccn_rh'], ),
    sa.PrimaryKeyConstraint('ccn_employee')
    )
    op.create_table('tbl_city',
    sa.Column('ccn_city', sa.Integer(), nullable=False),
    sa.Column('id_city', sa.Integer(), nullable=False),
    sa.Column('description_city', sa.String(length=60), nullable=False),
    sa.Column('ccn_department', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_department'], ['tbl_department.ccn_department'], ),
    sa.PrimaryKeyConstraint('ccn_city')
    )
    op.create_table('tbl_ss_employee',
    sa.Column('ccn_ss_employee', sa.Integer(), nullable=False),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('ccn_type_affiliation', sa.Integer(), nullable=True),
    sa.Column('ccn_type_contributor', sa.Integer(), nullable=True),
    sa.Column('ccn_eps', sa.Integer(), nullable=True),
    sa.Column('ccn_afp', sa.Integer(), nullable=True),
    sa.Column('ccn_arl', sa.Integer(), nullable=True),
    sa.Column('ccn_ccf', sa.Integer(), nullable=True),
    sa.Column('ccn_aap', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_aap'], ['tbl_aap.ccn_aap'], ),
    sa.ForeignKeyConstraint(['ccn_afp'], ['tbl_afp.ccn_afp'], ),
    sa.ForeignKeyConstraint(['ccn_arl'], ['tbl_arl.ccn_arl'], ),
    sa.ForeignKeyConstraint(['ccn_ccf'], ['tbl_ccf.ccn_ccf'], ),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employee.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_eps'], ['tbl_eps.ccn_eps'], ),
    sa.ForeignKeyConstraint(['ccn_type_affiliation'], ['tbl_type_affiliation.ccn_type_affiliation'], ),
    sa.ForeignKeyConstraint(['ccn_type_contributor'], ['tbl_type_contributor.ccn_type_contributor'], ),
    sa.PrimaryKeyConstraint('ccn_ss_employee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_ss_employee')
    op.drop_table('tbl_city')
    op.drop_table('tbl_employee')
    op.drop_table('tbl_department')
    op.drop_table('tbl_type_id')
    op.drop_table('tbl_type_contributor')
    op.drop_table('tbl_type_affiliation')
    op.drop_table('tbl_role')
    op.drop_table('tbl_rh')
    op.drop_table('tbl_eps')
    op.drop_table('tbl_country')
    op.drop_table('tbl_ccf')
    op.drop_table('tbl_auto_perceived_gender')
    op.drop_table('tbl_arl')
    op.drop_table('tbl_age_range')
    op.drop_table('tbl_afp')
    op.drop_table('tbl_aap')
    # ### end Alembic commands ###
