"""booleans

Revision ID: 4b4e28538a09
Revises: 225f1312c8f4
Create Date: 2023-04-03 09:29:47.049449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4e28538a09'
down_revision = '225f1312c8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_RBAC', sa.Column('create_access', sa.Boolean(), nullable=True))
    op.add_column('tbl_RBAC', sa.Column('read_access', sa.Boolean(), nullable=True))
    op.add_column('tbl_RBAC', sa.Column('update_access', sa.Boolean(), nullable=True))
    op.add_column('tbl_RBAC', sa.Column('delete_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_RBAC', 'delete_access')
    op.drop_column('tbl_RBAC', 'update_access')
    op.drop_column('tbl_RBAC', 'read_access')
    op.drop_column('tbl_RBAC', 'create_access')
    # ### end Alembic commands ###
