"""20221218_1849

Revision ID: 502c423c546d
Revises: ec9013abfb88
Create Date: 2022-12-18 08:49:09.470823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502c423c546d'
down_revision = 'ec9013abfb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employee', 'tbl_age_range', ['age_range'], ['ccn_age_range'])
    op.create_foreign_key(None, 'tbl_employee', 'tbl_rh', ['rh'], ['ccn_rh'])
    op.create_foreign_key(None, 'tbl_employee', 'tbl_type_id', ['ccn_type_id'], ['ccn_type_id'])
    op.create_foreign_key(None, 'tbl_employee', 'tbl_auto_perceived_gender', ['auto_perceived_gender'], ['ccn_auto_perceived_gender'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    # ### end Alembic commands ###
