"""20221209_0801

Revision ID: 539660525843
Revises: 1b2976760d64
Create Date: 2022-12-09 08:01:28.216774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539660525843'
down_revision = '1b2976760d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_house_type',
    sa.Column('ccn_house_type', sa.Integer(), nullable=False),
    sa.Column('house_type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('ccn_house_type')
    )
    op.create_table('tbl_marital_status',
    sa.Column('ccn_marital_status', sa.Integer(), nullable=False),
    sa.Column('marital_status', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('ccn_marital_status')
    )
    op.create_table('tbl_subhouse_type',
    sa.Column('ccn_sub_house_type', sa.Integer(), nullable=False),
    sa.Column('sub_house_type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('ccn_sub_house_type')
    )
    op.drop_constraint('tbl_sociodemographic_data_ibfk_3', 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_constraint('tbl_sociodemographic_data_ibfk_2', 'tbl_sociodemographic_data', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_subhouse_type', ['ccn_sub_house_type'], ['ccn_sub_house_type'])
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_house_type', ['ccn_house_type'], ['ccn_house_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.create_foreign_key('tbl_sociodemographic_data_ibfk_2', 'tbl_sociodemographic_data', 'tbl_employee', ['ccn_house_type'], ['ccn_employee'])
    op.create_foreign_key('tbl_sociodemographic_data_ibfk_3', 'tbl_sociodemographic_data', 'tbl_employee', ['ccn_sub_house_type'], ['ccn_employee'])
    op.drop_table('tbl_subhouse_type')
    op.drop_table('tbl_marital_status')
    op.drop_table('tbl_house_type')
    # ### end Alembic commands ###
