"""20221205_1226

Revision ID: 57f30cac23b0
Revises: 89f6910c0da5
Create Date: 2022-12-05 12:26:53.743574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f30cac23b0'
down_revision = '89f6910c0da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_relationship',
    sa.Column('ccn_relationship', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('relationship_level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ccn_relationship')
    )
    op.create_table('tbl_emergency_contact_details',
    sa.Column('ccn_emergency_contact_details', sa.Integer(), nullable=False),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=60), nullable=False),
    sa.Column('ccn_relationship', sa.Integer(), nullable=True),
    sa.Column('cellphone', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employee.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_relationship'], ['tbl_relationship.ccn_relationship'], ),
    sa.PrimaryKeyConstraint('ccn_emergency_contact_details')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_emergency_contact_details')
    op.drop_table('tbl_relationship')
    # ### end Alembic commands ###
