"""20230804_0932

Revision ID: 5bd2482cce5a
Revises: d377bd247213
Create Date: 2023-08-04 09:32:39.739758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd2482cce5a'
down_revision = 'd377bd247213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_country', ['country_residence'], ['ccn_country'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_country', ['birth_country'], ['ccn_country'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    # ### end Alembic commands ###
