"""Change Personal Cell Phone Big Integer

Revision ID: 5f46cf37dc49
Revises: cb3e569290d5
Create Date: 2023-01-30 11:25:53.951781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f46cf37dc49'
down_revision = 'cb3e569290d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('employee_personal_cellphone', sa.BigInteger(), nullable=False))
    op.drop_column('tbl_employee', 'test_employee_personal_cellphone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('test_employee_personal_cellphone', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('tbl_employee', 'employee_personal_cellphone')
    # ### end Alembic commands ###
