"""20221214_0925

Revision ID: 60750916a70f
Revises: 946a25a9b84e
Create Date: 2022-12-14 09:26:02.471619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60750916a70f'
down_revision = '946a25a9b84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_diseases',
    sa.Column('ccn_diseases', sa.Integer(), nullable=False),
    sa.Column('diseases', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('ccn_diseases')
    )
    op.drop_constraint('tbl_health_condition_ibfk_1', 'tbl_health_condition', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_health_condition', 'tbl_employee', ['diseases'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_health_condition', 'tbl_diseases', ['ccn_employee'], ['ccn_diseases'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_health_condition', type_='foreignkey')
    op.drop_constraint(None, 'tbl_health_condition', type_='foreignkey')
    op.create_foreign_key('tbl_health_condition_ibfk_1', 'tbl_health_condition', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.drop_table('tbl_diseases')
    # ### end Alembic commands ###
