"""20230623_0709

Revision ID: 6646f011cc89
Revises: d9a932d71866
Create Date: 2023-06-23 07:11:20.708093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6646f011cc89'
down_revision = 'd9a932d71866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employee', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    # ### end Alembic commands ###
