"""20230623_0653

Revision ID: 6b23f8431b09
Revises: fbbc9d7c753e
Create Date: 2023-06-23 06:53:30.391352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b23f8431b09'
down_revision = 'fbbc9d7c753e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_family_nucleus_ibfk_1', 'tbl_family_nucleus', type_='foreignkey')
    op.drop_column('tbl_family_nucleus', 'ccn_marital_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_family_nucleus', sa.Column('ccn_marital_status', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tbl_family_nucleus_ibfk_1', 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###
