"""20221207_1337

Revision ID: 6fb6d8537084
Revises: de873515aa0b
Create Date: 2022-12-07 13:37:37.552247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fb6d8537084'
down_revision = 'de873515aa0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_family_nucleus', sa.Column('ccn_marital_status', sa.String(length=40), nullable=False))
    op.drop_column('tbl_family_nucleus', 'civil_state')
    op.add_column('tbl_sociodemographic_data', sa.Column('ccn_sub_house_type', sa.Integer(), nullable=False))
    op.add_column('tbl_sociodemographic_data', sa.Column('ccn_house_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_employee', ['ccn_sub_house_type'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_employee', ['ccn_house_type'], ['ccn_employee'])
    op.drop_column('tbl_sociodemographic_data', 'house_type')
    op.drop_column('tbl_sociodemographic_data', 'sub_house_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_sociodemographic_data', sa.Column('sub_house_type', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('tbl_sociodemographic_data', sa.Column('house_type', mysql.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_column('tbl_sociodemographic_data', 'ccn_house_type')
    op.drop_column('tbl_sociodemographic_data', 'ccn_sub_house_type')
    op.add_column('tbl_family_nucleus', sa.Column('civil_state', mysql.VARCHAR(length=40), nullable=False))
    op.drop_column('tbl_family_nucleus', 'ccn_marital_status')
    # ### end Alembic commands ###
