"""20221203_1927

Revision ID: 71241c5516a0
Revises: d771ddc1dfb4
Create Date: 2022-12-03 19:27:34.442945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71241c5516a0'
down_revision = 'd771ddc1dfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_type_relationship',
    sa.Column('ccn_type_relationship', sa.Integer(), nullable=False),
    sa.Column('description_type_relationship', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ccn_type_relationship')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_type_relationship')
    # ### end Alembic commands ###
