"""20230323_1423

Revision ID: 71f5e96cbcf8
Revises: c24b672471f8
Create Date: 2023-03-23 14:23:41.979383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f5e96cbcf8'
down_revision = 'c24b672471f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_administrative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_directive_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_operative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_operative_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_directive_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_administrative_performance_evaluation', type_='foreignkey')
    # ### end Alembic commands ###
