"""20221218_1907

Revision ID: 7257b423907e
Revises: 7bc4e0f228a6
Create Date: 2022-12-18 09:07:09.600678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7257b423907e'
down_revision = '7bc4e0f228a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_ss_employee',
    sa.Column('ccn_ss_employee', sa.Integer(), nullable=False),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('ccn_type_affiliation', sa.Integer(), nullable=True),
    sa.Column('ccn_type_contributor', sa.Integer(), nullable=True),
    sa.Column('ccn_eps', sa.Integer(), nullable=True),
    sa.Column('ccn_afp', sa.Integer(), nullable=True),
    sa.Column('ccn_arl', sa.Integer(), nullable=True),
    sa.Column('ccn_ccf', sa.Integer(), nullable=True),
    sa.Column('ccn_aap', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_aap'], ['tbl_aap.ccn_aap'], ),
    sa.ForeignKeyConstraint(['ccn_afp'], ['tbl_afp.ccn_afp'], ),
    sa.ForeignKeyConstraint(['ccn_arl'], ['tbl_arl.ccn_arl'], ),
    sa.ForeignKeyConstraint(['ccn_ccf'], ['tbl_ccf.ccn_ccf'], ),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employee.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_eps'], ['tbl_eps.ccn_eps'], ),
    sa.ForeignKeyConstraint(['ccn_type_affiliation'], ['tbl_type_affiliation.ccn_type_affiliation'], ),
    sa.ForeignKeyConstraint(['ccn_type_contributor'], ['tbl_type_contributor.ccn_type_contributor'], ),
    sa.PrimaryKeyConstraint('ccn_ss_employee')
    )
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_department', ['department_residence'], ['ccn_department'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_city', ['city_residence'], ['ccn_city'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_race', ['ccn_race'], ['ccn_race'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_city', ['birth_city'], ['ccn_city'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_schooling_level', ['ccn_schooling_level'], ['ccn_schooling_level'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_department', ['birth_department'], ['ccn_department'])
    op.create_foreign_key(None, 'tbl_emergency_contact_details', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_emergency_contact_details', 'tbl_relationship', ['ccn_relationship'], ['ccn_relationship'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_roles', ['ccn_role'], ['ccn_role'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_type_relationship', ['ccn_type_relationship'], ['ccn_type_relationship'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_work_shift', ['ccn_work_shift'], ['ccn_work_shift'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_auto_perceived_gender', ['ccn_auto_perceived_gender'], ['ccn_auto_perceived_gender'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_type_id', ['ccn_type_id'], ['ccn_type_id'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_age_range', ['age_range'], ['ccn_age_range'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_schooling_level', ['ccn_schooling_level'], ['ccn_schooling_level'])
    op.create_foreign_key(None, 'tbl_health_condition', 'tbl_diseases', ['ccn_diseases'], ['ccn_diseases'])
    op.create_foreign_key(None, 'tbl_health_condition', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_house_type', ['ccn_house_type'], ['ccn_house_type'])
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_subhouse_type', ['ccn_sub_house_type'], ['ccn_sub_house_type'])
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_health_condition', type_='foreignkey')
    op.drop_constraint(None, 'tbl_health_condition', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_emergency_contact_details', type_='foreignkey')
    op.drop_constraint(None, 'tbl_emergency_contact_details', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_table('tbl_ss_employee')
    # ### end Alembic commands ###
