"""20230428_1119

Revision ID: 741a18126b62
Revises: 4b4e28538a09
Create Date: 2023-04-28 11:19:09.943305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741a18126b62'
down_revision = '4b4e28538a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_administrative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_directive_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_operative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_operative_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_directive_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_administrative_performance_evaluation', type_='foreignkey')
    # ### end Alembic commands ###
