"""20221221_1531

Revision ID: 756c5a362598
Revises: 0bd99cd726ff
Create Date: 2022-12-21 15:31:41.494335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '756c5a362598'
down_revision = '0bd99cd726ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_family_nucleus', 'number_of_children',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'number_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'first_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'middle_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'first_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'second_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_family_nucleus', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'second_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'first_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'middle_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'first_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'number_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'number_of_children',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
