"""20220228_1235

Revision ID: 768bd5da76ed
Revises: 234e648f7dcd
Create Date: 2023-02-28 12:35:45.376116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768bd5da76ed'
down_revision = '234e648f7dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['immediate_boss'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    # ### end Alembic commands ###
