"""20230615_1234

Revision ID: 79f940e53d4b
Revises: 426efd13e67c
Create Date: 2023-06-15 12:34:04.301657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79f940e53d4b'
down_revision = '426efd13e67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_family_nucleus_ibfk_1', 'tbl_family_nucleus', type_='foreignkey')
    op.drop_column('tbl_family_nucleus', 'ccn_marital_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_family_nucleus', sa.Column('ccn_marital_status', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tbl_family_nucleus_ibfk_1', 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###
