"""20220301_0836

Revision ID: 812dfee412f1
Revises: a6b710adaa8e
Create Date: 2023-03-01 08:36:28.499717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '812dfee412f1'
down_revision = 'a6b710adaa8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_employment_relationship', 'pending_days_to_enjoy_for_holidays',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_employment_relationship', 'pending_days_to_enjoy_for_holidays',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
