"""20221214_0927

Revision ID: 82fb877fb1e1
Revises: 60750916a70f
Create Date: 2022-12-14 09:27:37.894771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82fb877fb1e1'
down_revision = '60750916a70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_health_condition', sa.Column('ccn_diseases', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tbl_health_condition', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_health_condition', 'tbl_diseases', ['ccn_diseases'], ['ccn_diseases'])
    op.drop_column('tbl_health_condition', 'diseases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_health_condition', sa.Column('diseases', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'tbl_health_condition', type_='foreignkey')
    op.drop_constraint(None, 'tbl_health_condition', type_='foreignkey')
    op.drop_column('tbl_health_condition', 'ccn_diseases')
    # ### end Alembic commands ###
