"""20230623_0709

Revision ID: 84645237d6c2
Revises: 6646f011cc89
Create Date: 2023-06-23 07:11:27.375909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84645237d6c2'
down_revision = '6646f011cc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employee', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    # ### end Alembic commands ###
