"""20221218_2022

Revision ID: 8488e4f272f7
Revises: 502c423c546d
Create Date: 2022-12-18 08:53:31.244562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8488e4f272f7'
down_revision = '502c423c546d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employee', 'tbl_auto_perceived_gender', ['auto_perceived_gender'], ['ccn_auto_perceived_gender'])
    op.create_foreign_key(None, 'tbl_employee', 'tbl_age_range', ['age_range'], ['ccn_age_range'])
    op.create_foreign_key(None, 'tbl_employee', 'tbl_type_id', ['ccn_type_id'], ['ccn_type_id'])
    op.create_foreign_key(None, 'tbl_employee', 'tbl_rh', ['rh'], ['ccn_rh'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_type_affiliation', ['ccn_type_affiliation'], ['ccn_type_affiliation'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_aap', ['ccn_aap'], ['ccn_aap'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_afp', ['ccn_afp'], ['ccn_afp'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_arl', ['ccn_arl'], ['ccn_arl'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_ccf', ['ccn_ccf'], ['ccn_ccf'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_type_contributor', ['ccn_type_contributor'], ['ccn_type_contributor'])
    op.create_foreign_key(None, 'tbl_ss_employee', 'tbl_eps', ['ccn_eps'], ['ccn_eps'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_ss_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employee', type_='foreignkey')
    # ### end Alembic commands ###
