"""20221205_1224

Revision ID: 89f6910c0da5
Revises: c7b82ddc9f85
Create Date: 2022-12-05 12:24:11.035526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f6910c0da5'
down_revision = 'c7b82ddc9f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_city', ['city_residence'], ['ccn_city'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_department', ['department_residence'], ['ccn_department'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    # ### end Alembic commands ###
