"""20230510_0911

Revision ID: 8b68fe3f9525
Revises: 0b74c21dae07
Create Date: 2023-05-10 09:11:15.600974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b68fe3f9525'
down_revision = '0b74c21dae07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_employment_relationship', 'manager',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['manager'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.alter_column('tbl_employment_relationship', 'manager',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
