"""20221207_0958

Revision ID: 8ea52319af6b
Revises: 57f30cac23b0
Create Date: 2022-12-07 09:58:30.266093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea52319af6b'
down_revision = '57f30cac23b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_family_nucleus',
    sa.Column('ccn_family_nucleus', sa.Integer(), nullable=False),
    sa.Column('civil_state', sa.String(length=40), nullable=False),
    sa.Column('number_of_children', sa.Integer(), nullable=False),
    sa.Column('type_of_document', sa.String(length=40), nullable=False),
    sa.Column('number_id_employee', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=False),
    sa.Column('first_last_name', sa.String(length=30), nullable=False),
    sa.Column('second_last_name', sa.String(length=30), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.String(length=100), nullable=False),
    sa.Column('scholarship', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_family_nucleus')
    )
    op.create_table('tbl_health_condition',
    sa.Column('ccn_health_condition', sa.Integer(), nullable=False),
    sa.Column('consume_alcoholic_beverages', sa.String(length=50), nullable=False),
    sa.Column('diseases', sa.String(length=255), nullable=False),
    sa.Column('allergies', sa.String(length=50), nullable=False),
    sa.Column('what_allergy', sa.String(length=255), nullable=False),
    sa.Column('medicines', sa.String(length=50), nullable=False),
    sa.Column('what_medicin', sa.String(length=255), nullable=False),
    sa.Column('last_medical_consultation', sa.String(length=255), nullable=False),
    sa.Column('plan_to_drink_less_alcoholic_beverages', sa.String(length=50), nullable=False),
    sa.Column('discomfort_due_to_criticism_when_ingesting_alcohol', sa.String(length=50), nullable=False),
    sa.Column('need_to_drink_alcohol_in_the_morning', sa.String(length=50), nullable=False),
    sa.Column('physical_activity_3_times_a_week_30_minutes', sa.String(length=50), nullable=False),
    sa.Column('he_is_a_smoker', sa.String(length=50), nullable=False),
    sa.Column('how_many_cigarettes_a_day', sa.Integer(), nullable=False),
    sa.Column('he_is_ex_smoker', sa.String(length=50), nullable=False),
    sa.Column('consume_psychoactive_substances', sa.String(length=50), nullable=False),
    sa.Column('used_psychoactive_substances_before', sa.String(length=50), nullable=False),
    sa.Column('what_psychoactive_substances', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ccn_health_condition')
    )
    op.create_table('tbl_sociodemographic_data',
    sa.Column('ccn_sociodemographic_data', sa.Integer(), nullable=False),
    sa.Column('other_dependents', sa.String(length=50), nullable=False),
    sa.Column('number_of_people_in_the_home', sa.Integer(), nullable=False),
    sa.Column('number_of_people_with_disabilities', sa.Integer(), nullable=False),
    sa.Column('monthly_household_income', sa.Integer(), nullable=False),
    sa.Column('income_reaches', sa.String(length=50), nullable=False),
    sa.Column('housing_type', sa.String(length=150), nullable=False),
    sa.Column('features_of_housing', sa.String(length=150), nullable=False),
    sa.Column('area_where_its_located', sa.String(length=100), nullable=False),
    sa.Column('residence_address', sa.String(length=150), nullable=False),
    sa.Column('type_of_transport_to_go_to_work', sa.String(length=150), nullable=False),
    sa.Column('public_services_stratum', sa.Integer(), nullable=False),
    sa.Column('electric_power', sa.String(length=50), nullable=False),
    sa.Column('sewerage', sa.String(length=50), nullable=False),
    sa.Column('aqueduct', sa.String(length=50), nullable=False),
    sa.Column('natural_gas', sa.String(length=50), nullable=False),
    sa.Column('garbage_collection', sa.String(length=50), nullable=False),
    sa.Column('landline', sa.Integer(), nullable=False),
    sa.Column('debts', sa.String(length=50), nullable=False),
    sa.Column('debt_refinancing', sa.String(length=50), nullable=False),
    sa.Column('computer_at_home', sa.String(length=50), nullable=False),
    sa.Column('have_internet_access', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ccn_sociodemographic_data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_sociodemographic_data')
    op.drop_table('tbl_health_condition')
    op.drop_table('tbl_family_nucleus')
    # ### end Alembic commands ###
