"""20221209_0803

Revision ID: 8f99679925d3
Revises: 539660525843
Create Date: 2022-12-09 08:04:10.190149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f99679925d3'
down_revision = '539660525843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    # ### end Alembic commands ###
