"""20221207_1049

Revision ID: 941ac04efc45
Revises: f2689fb79b46
Create Date: 2022-12-07 10:49:16.164207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941ac04efc45'
down_revision = 'f2689fb79b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_roles', sa.Column('full_role', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_roles', 'full_role')
    # ### end Alembic commands ###
