"""20230307_0710

Revision ID: a2ccb89664fd
Revises: 0eb8db52a599
Create Date: 2023-03-07 07:10:57.768161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ccb89664fd'
down_revision = '0eb8db52a599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_main_access_control',
    sa.Column('ccn_main_access_control', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=False),
    sa.Column('hour', sa.String(length=20), nullable=False),
    sa.Column('number_id_employee', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('observations', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('ccn_main_access_control')
    )
    op.create_table('tbl_states_performance_evaluation',
    sa.Column('ccn_states_performance_evaluation', sa.Integer(), nullable=False),
    sa.Column('states_performance_evaluation', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ccn_states_performance_evaluation')
    )
    op.create_table('tbl_performance_evaluation',
    sa.Column('ccn_performance_evaluation', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('immediate_boss', sa.Integer(), nullable=True),
    sa.Column('manager', sa.Integer(), nullable=True),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('ccn_states_performance_evaluation', sa.Integer(), nullable=True),
    sa.Column('type_employee', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employment_relationship.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_states_performance_evaluation'], ['tbl_states_performance_evaluation.ccn_states_performance_evaluation'], ),
    sa.ForeignKeyConstraint(['immediate_boss'], ['tbl_employment_relationship.ccn_employee'], ),
    sa.ForeignKeyConstraint(['manager'], ['tbl_employment_relationship.ccn_employee'], ),
    sa.PrimaryKeyConstraint('ccn_performance_evaluation')
    )
    op.create_table('tbl_administrative_performance_evaluation',
    sa.Column('ccn_administrative_performance_evaluation', sa.Integer(), nullable=False),
    sa.Column('ccn_performance_evaluation', sa.Integer(), nullable=True),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('engagement_or_productivity', sa.String(length=10), nullable=False),
    sa.Column('communication_skills', sa.String(length=10), nullable=False),
    sa.Column('adaptation_to_change', sa.String(length=10), nullable=False),
    sa.Column('customer_orientation', sa.String(length=10), nullable=False),
    sa.Column('innovation', sa.String(length=10), nullable=False),
    sa.Column('professional_rigor', sa.String(length=10), nullable=False),
    sa.Column('problem_resolution', sa.String(length=10), nullable=False),
    sa.Column('leadership', sa.String(length=10), nullable=False),
    sa.Column('organization', sa.String(length=10), nullable=False),
    sa.Column('employee_response', sa.String(length=300), nullable=False),
    sa.Column('first_action_plan', sa.String(length=50), nullable=False),
    sa.Column('first_action_plan_date', sa.Date(), nullable=True),
    sa.Column('first_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('second_action_plan', sa.String(length=50), nullable=False),
    sa.Column('second_action_plan_date', sa.Date(), nullable=True),
    sa.Column('second_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('third_action_plan', sa.String(length=50), nullable=False),
    sa.Column('third_action_plan_date', sa.Date(), nullable=True),
    sa.Column('third_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('manager_response', sa.String(length=250), nullable=False),
    sa.Column('manager_approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employment_relationship.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_performance_evaluation'], ['tbl_performance_evaluation.ccn_performance_evaluation'], ),
    sa.PrimaryKeyConstraint('ccn_administrative_performance_evaluation')
    )
    op.create_table('tbl_directive_performance_evaluation',
    sa.Column('ccn_directive_performance_evaluation', sa.Integer(), nullable=False),
    sa.Column('ccn_performance_evaluation', sa.Integer(), nullable=True),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('engagement_or_productivity', sa.String(length=10), nullable=False),
    sa.Column('communication_skills', sa.String(length=10), nullable=False),
    sa.Column('adaptation_to_change', sa.String(length=10), nullable=False),
    sa.Column('customer_orientation', sa.String(length=10), nullable=False),
    sa.Column('innovation', sa.String(length=10), nullable=False),
    sa.Column('professional_rigor', sa.String(length=10), nullable=False),
    sa.Column('problem_resolution', sa.String(length=10), nullable=False),
    sa.Column('leadership', sa.String(length=10), nullable=False),
    sa.Column('organization', sa.String(length=10), nullable=False),
    sa.Column('employee_response', sa.String(length=300), nullable=False),
    sa.Column('first_action_plan', sa.String(length=50), nullable=False),
    sa.Column('first_action_plan_date', sa.Date(), nullable=True),
    sa.Column('first_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('second_action_plan', sa.String(length=50), nullable=False),
    sa.Column('second_action_plan_date', sa.Date(), nullable=True),
    sa.Column('second_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('third_action_plan', sa.String(length=50), nullable=False),
    sa.Column('third_action_plan_date', sa.Date(), nullable=True),
    sa.Column('third_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('manager_response', sa.String(length=250), nullable=False),
    sa.Column('manager_approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employment_relationship.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_performance_evaluation'], ['tbl_performance_evaluation.ccn_performance_evaluation'], ),
    sa.PrimaryKeyConstraint('ccn_directive_performance_evaluation')
    )
    op.create_table('tbl_operative_performance_evaluation',
    sa.Column('ccn_operative_performance_evaluation', sa.Integer(), nullable=False),
    sa.Column('ccn_performance_evaluation', sa.Integer(), nullable=True),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('engagement_or_productivity', sa.String(length=10), nullable=False),
    sa.Column('communication_skills', sa.String(length=10), nullable=False),
    sa.Column('adaptation_to_change', sa.String(length=10), nullable=False),
    sa.Column('learning_and_development', sa.String(length=10), nullable=False),
    sa.Column('organization', sa.String(length=10), nullable=False),
    sa.Column('continuous_improvement', sa.String(length=10), nullable=False),
    sa.Column('active_participation', sa.String(length=10), nullable=False),
    sa.Column('relations', sa.String(length=10), nullable=False),
    sa.Column('puntuality', sa.String(length=10), nullable=False),
    sa.Column('employee_response', sa.String(length=300), nullable=False),
    sa.Column('first_action_plan', sa.String(length=50), nullable=False),
    sa.Column('first_action_plan_date', sa.Date(), nullable=True),
    sa.Column('first_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('second_action_plan', sa.String(length=50), nullable=False),
    sa.Column('second_action_plan_date', sa.Date(), nullable=True),
    sa.Column('second_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('third_action_plan', sa.String(length=50), nullable=False),
    sa.Column('third_action_plan_date', sa.Date(), nullable=True),
    sa.Column('third_period_of_execution', sa.String(length=100), nullable=False),
    sa.Column('manager_response', sa.String(length=250), nullable=False),
    sa.Column('manager_approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employment_relationship.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_performance_evaluation'], ['tbl_performance_evaluation.ccn_performance_evaluation'], ),
    sa.PrimaryKeyConstraint('ccn_operative_performance_evaluation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_operative_performance_evaluation')
    op.drop_table('tbl_directive_performance_evaluation')
    op.drop_table('tbl_administrative_performance_evaluation')
    op.drop_table('tbl_performance_evaluation')
    op.drop_table('tbl_states_performance_evaluation')
    op.drop_table('tbl_main_access_control')
    # ### end Alembic commands ###
