"""20220301_0809

Revision ID: a6b710adaa8e
Revises: 06875d5f797b
Create Date: 2023-03-01 08:09:43.108697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b710adaa8e'
down_revision = '06875d5f797b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['manager'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['immediate_boss'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    # ### end Alembic commands ###
