"""20221209_0803

Revision ID: a71f50efa201
Revises: 40163005c8f3
Create Date: 2022-12-09 08:07:01.570451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71f50efa201'
down_revision = '40163005c8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    # ### end Alembic commands ###
