"""20221229_1040

Revision ID: abc8501423b1
Revises: 5009fa951468
Create Date: 2022-12-29 10:40:17.422212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc8501423b1'
down_revision = '5009fa951468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_city_ibfk_1', 'tbl_city', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_city', 'tbl_department', ['ccn_department'], ['id_department'])
    op.add_column('tbl_employment_relationship', sa.Column('immediate_boss', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employment_relationship', 'immediate_boss')
    op.drop_constraint(None, 'tbl_city', type_='foreignkey')
    op.create_foreign_key('tbl_city_ibfk_1', 'tbl_city', 'tbl_department', ['ccn_department'], ['ccn_department'])
    # ### end Alembic commands ###
