"""test_new_data

Revision ID: b95f5141fe55
Revises: 5f46cf37dc49
Create Date: 2023-02-28 22:29:57.451517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95f5141fe55'
down_revision = '5f46cf37dc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employee', 'last_message_read_time')
    # ### end Alembic commands ###
