"""20230313_1720

Revision ID: bad5ee7282ee
Revises: 19cca12d173d
Create Date: 2023-03-13 17:20:13.712122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad5ee7282ee'
down_revision = '19cca12d173d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_performance_evaluation', sa.Column('immediate_boss_question_date', sa.DateTime(), nullable=True))
    op.add_column('tbl_performance_evaluation', sa.Column('employee_response_date', sa.Date(), nullable=True))
    op.add_column('tbl_performance_evaluation', sa.Column('action_plan_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_performance_evaluation', 'action_plan_date')
    op.drop_column('tbl_performance_evaluation', 'employee_response_date')
    op.drop_column('tbl_performance_evaluation', 'immediate_boss_question_date')
    # ### end Alembic commands ###
