"""Change Personal Cell Phone Big Integer

Revision ID: cb3e569290d5
Revises: 97dc8c3a44a7
Create Date: 2023-01-30 11:25:25.813687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb3e569290d5'
down_revision = '97dc8c3a44a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('test_employee_personal_cellphone', sa.BigInteger(), nullable=False))
    op.drop_column('tbl_employee', 'employee_personal_cellphone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('employee_personal_cellphone', mysql.VARCHAR(length=40), nullable=False))
    op.drop_column('tbl_employee', 'test_employee_personal_cellphone')
    # ### end Alembic commands ###
