"""20230307_2235

Revision ID: cc0e45e4927c
Revises: ff5a391274c5
Create Date: 2023-03-07 22:35:42.974899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0e45e4927c'
down_revision = 'ff5a391274c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_main_access_control', sa.Column('event', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_main_access_control', 'event')
    # ### end Alembic commands ###
