"""20221229_1100

Revision ID: d0a38a06eea9
Revises: 4babb279cf58
Create Date: 2022-12-29 11:00:45.273617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a38a06eea9'
down_revision = '4babb279cf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('foreign_key_city', 'tbl_city', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_city', 'tbl_department', ['ccn_department'], ['id_department'])
    op.add_column('tbl_employment_relationship', sa.Column('immediate_boss', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employment_relationship', 'immediate_boss')
    op.drop_constraint(None, 'tbl_city', type_='foreignkey')
    op.create_foreign_key('foreign_key_city', 'tbl_city', 'tbl_department', ['ccn_department'], ['ccn_department'])
    # ### end Alembic commands ###
