"""20230323_1127

Revision ID: d25cfca0776f
Revises: 9888cb39c58b
Create Date: 2023-03-23 11:28:02.380299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25cfca0776f'
down_revision = '9888cb39c58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_directive_performance_evaluation',
    sa.Column('ccn_directive_performance_evaluation', sa.Integer(), nullable=False),
    sa.Column('ccn_performance_evaluation', sa.Integer(), nullable=True),
    sa.Column('ccn_employee', sa.Integer(), nullable=True),
    sa.Column('engagement_or_productivity', sa.String(length=10), nullable=True),
    sa.Column('communication_skills', sa.String(length=10), nullable=True),
    sa.Column('adaptation_to_change', sa.String(length=10), nullable=True),
    sa.Column('customer_orientation', sa.String(length=10), nullable=True),
    sa.Column('innovation', sa.String(length=10), nullable=True),
    sa.Column('professional_rigor', sa.String(length=10), nullable=True),
    sa.Column('problem_resolution', sa.String(length=10), nullable=True),
    sa.Column('leadership', sa.String(length=10), nullable=True),
    sa.Column('organization', sa.String(length=10), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('level_value', sa.String(length=50), nullable=True),
    sa.Column('employee_response', sa.String(length=300), nullable=True),
    sa.Column('first_action_plan', sa.String(length=50), nullable=True),
    sa.Column('first_action_plan_date', sa.Date(), nullable=True),
    sa.Column('first_period_of_execution', sa.String(length=100), nullable=True),
    sa.Column('second_action_plan', sa.String(length=50), nullable=True),
    sa.Column('second_action_plan_date', sa.Date(), nullable=True),
    sa.Column('second_period_of_execution', sa.String(length=100), nullable=True),
    sa.Column('third_action_plan', sa.String(length=50), nullable=True),
    sa.Column('third_action_plan_date', sa.Date(), nullable=True),
    sa.Column('third_period_of_execution', sa.String(length=100), nullable=True),
    sa.Column('immediate_boss_observation', sa.String(length=100), nullable=True),
    sa.Column('manager_response', sa.String(length=250), nullable=True),
    sa.Column('manager_approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employment_relationship.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_performance_evaluation'], ['tbl_performance_evaluation.ccn_performance_evaluation'], ),
    sa.PrimaryKeyConstraint('ccn_directive_performance_evaluation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_directive_performance_evaluation')
    # ### end Alembic commands ###
