"""20230804_0931

Revision ID: d377bd247213
Revises: 31ddfdae1590
Create Date: 2023-08-04 09:31:15.888145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd377bd247213'
down_revision = '31ddfdae1590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_demographic_data_ibfk_10', 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint('tbl_demographic_data_ibfk_11', 'tbl_demographic_data', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tbl_demographic_data_ibfk_11', 'tbl_demographic_data', 'tbl_country', ['birth_country'], ['ccn_country'])
    op.create_foreign_key('tbl_demographic_data_ibfk_10', 'tbl_demographic_data', 'tbl_country', ['country_residence'], ['ccn_country'])
    # ### end Alembic commands ###
