"""20221201_1735

Revision ID: d3cf6c7a1df7
Revises: 26533df28f02
Create Date: 2022-12-01 17:36:32.761032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3cf6c7a1df7'
down_revision = '26533df28f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('process', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ccn_role')
    )
    op.drop_table('tbl_role')
    op.alter_column('tbl_employment_relationship', 'ccn_role',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_roles', ['ccn_role'], ['ccn_role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.alter_column('tbl_employment_relationship', 'ccn_role',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_table('tbl_role',
    sa.Column('ccn_role', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('process', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ccn_role'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tbl_roles')
    # ### end Alembic commands ###
