"""20221223_0715

Revision ID: d5e62ae45295
Revises: 7cbe64b0cc1a
Create Date: 2022-12-23 07:15:43.414807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5e62ae45295'
down_revision = '7cbe64b0cc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_family_nucleus', 'number_of_children',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'number_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'first_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'middle_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'first_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'second_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tbl_family_nucleus', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('tbl_sociodemographic_data', sa.Column('type_transportation_2', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_sociodemographic_data', 'type_transportation_2')
    op.alter_column('tbl_family_nucleus', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'second_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'first_last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'middle_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'first_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'number_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tbl_family_nucleus', 'number_of_children',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
