"""20221201_2003

Revision ID: d771ddc1dfb4
Revises: d3cf6c7a1df7
Create Date: 2022-12-01 20:03:15.572268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd771ddc1dfb4'
down_revision = 'd3cf6c7a1df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employment_relationship', sa.Column('binding_date', sa.Date(), nullable=False))
    op.add_column('tbl_employment_relationship', sa.Column('termination_date', sa.Date(), nullable=False))
    op.drop_column('tbl_employment_relationship', 'ccn_binding_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employment_relationship', sa.Column('ccn_binding_date', sa.DATE(), nullable=False))
    op.drop_column('tbl_employment_relationship', 'termination_date')
    op.drop_column('tbl_employment_relationship', 'binding_date')
    # ### end Alembic commands ###
