"""20221209_1542

Revision ID: d9c38221149f
Revises: 1da3c066b569
Create Date: 2022-12-09 15:42:55.253078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9c38221149f'
down_revision = '1da3c066b569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_family_nucleus', sa.Column('number_id', sa.Integer(), nullable=False))
    op.add_column('tbl_family_nucleus', sa.Column('ccn_schooling_level', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_schooling_level', ['ccn_schooling_level'], ['ccn_schooling_level'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_age_range', ['age_range'], ['ccn_age_range'])
    op.create_foreign_key(None, 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    op.drop_column('tbl_family_nucleus', 'scholarship')
    op.drop_column('tbl_family_nucleus', 'number_id_employee')
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_house_type', ['ccn_house_type'], ['ccn_house_type'])
    op.create_foreign_key(None, 'tbl_sociodemographic_data', 'tbl_subhouse_type', ['ccn_sub_house_type'], ['ccn_sub_house_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='foreignkey')
    op.add_column('tbl_family_nucleus', sa.Column('number_id_employee', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tbl_family_nucleus', sa.Column('scholarship', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family_nucleus', type_='foreignkey')
    op.drop_column('tbl_family_nucleus', 'ccn_schooling_level')
    op.drop_column('tbl_family_nucleus', 'number_id')
    # ### end Alembic commands ###
