"""20221229_1215

Revision ID: dad0a7029e68
Revises: 29089e68096b
Create Date: 2022-12-29 12:15:38.666254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad0a7029e68'
down_revision = '29089e68096b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_city', 'tbl_department', ['ccn_department'], ['ccn_department'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_city', ['birth_city'], ['ccn_city'])
    op.create_foreign_key(None, 'tbl_demographic_data', 'tbl_city', ['city_residence'], ['ccn_city'])
    op.add_column('tbl_employment_relationship', sa.Column('immediate_boss', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employment_relationship', 'immediate_boss')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_demographic_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_city', type_='foreignkey')
    # ### end Alembic commands ###
