"""20221207_1108

Revision ID: de873515aa0b
Revises: 941ac04efc45
Create Date: 2022-12-07 11:08:56.181928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de873515aa0b'
down_revision = '941ac04efc45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_family_nucleus',
    sa.Column('ccn_family_nucleus', sa.Integer(), nullable=False),
    sa.Column('ccn_employee', sa.Integer(), nullable=False),
    sa.Column('civil_state', sa.String(length=40), nullable=False),
    sa.Column('number_of_children', sa.Integer(), nullable=False),
    sa.Column('ccn_type_id', sa.Integer(), nullable=False),
    sa.Column('number_id_employee', sa.Integer(), nullable=False),
    sa.Column('ccn_auto_perceived_gender', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=False),
    sa.Column('first_last_name', sa.String(length=30), nullable=False),
    sa.Column('second_last_name', sa.String(length=30), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.String(length=100), nullable=False),
    sa.Column('scholarship', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ccn_auto_perceived_gender'], ['tbl_auto_perceived_gender.ccn_auto_perceived_gender'], ),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employee.ccn_employee'], ),
    sa.ForeignKeyConstraint(['ccn_type_id'], ['tbl_type_id.ccn_type_id'], ),
    sa.PrimaryKeyConstraint('ccn_family_nucleus')
    )
    op.create_table('tbl_health_condition',
    sa.Column('ccn_health_condition', sa.Integer(), nullable=False),
    sa.Column('ccn_employee', sa.Integer(), nullable=False),
    sa.Column('consume_alcoholic_beverages', sa.String(length=50), nullable=False),
    sa.Column('diseases', sa.String(length=255), nullable=False),
    sa.Column('allergies', sa.String(length=50), nullable=False),
    sa.Column('what_allergy', sa.String(length=255), nullable=True),
    sa.Column('medicines', sa.String(length=50), nullable=False),
    sa.Column('what_medicin', sa.String(length=255), nullable=True),
    sa.Column('last_medical_consultation', sa.String(length=255), nullable=False),
    sa.Column('plan_to_drink_less_alcoholic_beverages', sa.String(length=50), nullable=False),
    sa.Column('discomfort_due_to_criticism_when_ingesting_alcohol', sa.String(length=50), nullable=False),
    sa.Column('need_to_drink_alcohol_in_the_morning', sa.String(length=50), nullable=False),
    sa.Column('physical_activity_3_times_a_week_30_minutes', sa.String(length=50), nullable=False),
    sa.Column('he_is_a_smoker', sa.String(length=50), nullable=False),
    sa.Column('how_many_cigarettes_a_day', sa.Integer(), nullable=False),
    sa.Column('he_is_ex_smoker', sa.String(length=50), nullable=False),
    sa.Column('consume_psychoactive_substances', sa.String(length=50), nullable=False),
    sa.Column('used_psychoactive_substances_before', sa.String(length=50), nullable=False),
    sa.Column('what_psychoactive_substances', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employee.ccn_employee'], ),
    sa.PrimaryKeyConstraint('ccn_health_condition')
    )
    op.create_table('tbl_sociodemographic_data',
    sa.Column('ccn_sociodemographic_data', sa.Integer(), nullable=False),
    sa.Column('ccn_employee', sa.Integer(), nullable=False),
    sa.Column('other_dependents', sa.String(length=50), nullable=False),
    sa.Column('relatives', sa.Integer(), nullable=False),
    sa.Column('people_with_disabilities', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('is_income_enougth', sa.String(length=50), nullable=False),
    sa.Column('sub_house_type', sa.String(length=150), nullable=False),
    sa.Column('house_type', sa.String(length=150), nullable=False),
    sa.Column('where_its_located', sa.String(length=100), nullable=False),
    sa.Column('residence_address', sa.String(length=150), nullable=False),
    sa.Column('type_transportation', sa.String(length=150), nullable=False),
    sa.Column('social_stratum', sa.Integer(), nullable=False),
    sa.Column('electric_power', sa.String(length=50), nullable=False),
    sa.Column('sewerage', sa.String(length=50), nullable=False),
    sa.Column('aqueduct', sa.String(length=50), nullable=False),
    sa.Column('natural_gas', sa.String(length=50), nullable=False),
    sa.Column('garbage_collection', sa.String(length=50), nullable=False),
    sa.Column('landline', sa.Integer(), nullable=False),
    sa.Column('debts', sa.String(length=50), nullable=False),
    sa.Column('debt_refinancing', sa.String(length=50), nullable=False),
    sa.Column('computer_at_home', sa.String(length=50), nullable=False),
    sa.Column('have_internet_access', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ccn_employee'], ['tbl_employee.ccn_employee'], ),
    sa.PrimaryKeyConstraint('ccn_sociodemographic_data')
    )
    op.add_column('tbl_roles', sa.Column('full_role', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_roles', 'full_role')
    op.drop_table('tbl_sociodemographic_data')
    op.drop_table('tbl_health_condition')
    op.drop_table('tbl_family_nucleus')
    # ### end Alembic commands ###
