"""20230303_1206

Revision ID: e694e1c9203c
Revises: d25cfca0776f
Create Date: 2023-03-23 12:06:19.993424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e694e1c9203c'
down_revision = 'd25cfca0776f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_administrative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_directive_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    op.create_foreign_key(None, 'tbl_operative_performance_evaluation', 'tbl_performance_evaluation', ['ccn_performance_evaluation'], ['ccn_performance_evaluation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_operative_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_directive_performance_evaluation', type_='foreignkey')
    op.drop_constraint(None, 'tbl_administrative_performance_evaluation', type_='foreignkey')
    # ### end Alembic commands ###
