"""20221216_1844

Revision ID: ec9013abfb88
Revises: 3edc4d74643b
Create Date: 2022-12-16 18:44:45.502503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9013abfb88'
down_revision = '3edc4d74643b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['ccn_employee'], ['ccn_employee'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_work_shift', ['ccn_work_shift'], ['ccn_work_shift'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_roles', ['ccn_role'], ['ccn_role'])
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_type_relationship', ['ccn_type_relationship'], ['ccn_type_relationship'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    # ### end Alembic commands ###
