"""20221229_1044

Revision ID: f42c705f92cd
Revises: abc8501423b1
Create Date: 2022-12-29 10:44:46.790121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42c705f92cd'
down_revision = 'abc8501423b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_city', 'tbl_department', ['ccn_department'], ['id_department'])
    op.add_column('tbl_employment_relationship', sa.Column('immediate_boss', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employment_relationship', 'immediate_boss')
    op.drop_constraint(None, 'tbl_city', type_='foreignkey')
    # ### end Alembic commands ###
