"""20232806_1134

Revision ID: f52fce51c391
Revises: 3e1317166bbb
Create Date: 2023-06-28 11:34:21.685176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52fce51c391'
down_revision = '3e1317166bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_health_condition', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_sociodemographic_data', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_ss_employee', ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_ss_employee', type_='unique')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='unique')
    op.drop_constraint(None, 'tbl_health_condition', type_='unique')
    # ### end Alembic commands ###
