"""20230809_0806

Revision ID: f63b29b11693
Revises: 7bff71f2c850
Create Date: 2023-08-09 08:06:35.962314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63b29b11693'
down_revision = '7bff71f2c850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_trial_time_evaluation', sa.Column('date_immediate_boss', sa.Date(), nullable=False))
    op.drop_column('tbl_trial_time_evaluation', 'date_employee_boss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_trial_time_evaluation', sa.Column('date_employee_boss', sa.DATE(), nullable=False))
    op.drop_column('tbl_trial_time_evaluation', 'date_immediate_boss')
    # ### end Alembic commands ###
