"""test

Revision ID: fa6a6ed89b0d
Revises: e210e54d7e9a
Create Date: 2023-03-29 14:10:20.060853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6a6ed89b0d'
down_revision = 'e210e54d7e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_RBAC_modules',
    sa.Column('ccn_rbac_module', sa.Integer(), nullable=False),
    sa.Column('rbac_module', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ccn_rbac_module')
    )
    op.create_table('tbl_RBAC',
    sa.Column('ccn_rbac', sa.Integer(), nullable=False),
    sa.Column('ccn_role', sa.Integer(), nullable=True),
    sa.Column('ccn_rbac_module', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccn_rbac_module'], ['tbl_RBAC_modules.ccn_rbac_module'], ),
    sa.ForeignKeyConstraint(['ccn_role'], ['tbl_roles.ccn_role'], ),
    sa.PrimaryKeyConstraint('ccn_rbac')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_RBAC')
    op.drop_table('tbl_RBAC_modules')
    # ### end Alembic commands ###
