"""20230629_0750

Revision ID: fc96f7854bda
Revises: df4c5e728953
Create Date: 2023-06-29 07:50:18.179830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc96f7854bda'
down_revision = 'df4c5e728953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_demographic_data', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_emergency_contact_details', ['ccn_employee'])
    op.add_column('tbl_employee', sa.Column('ccn_marital_status', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'tbl_employee', ['number_id_employee'])
    op.create_unique_constraint(None, 'tbl_employment_relationship', ['ccn_employee'])
    op.drop_constraint('tbl_family_nucleus_ibfk_1', 'tbl_family_nucleus', type_='foreignkey')
    op.drop_column('tbl_family_nucleus', 'ccn_marital_status')
    op.create_unique_constraint(None, 'tbl_health_condition', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_sociodemographic_data', ['ccn_employee'])
    op.create_unique_constraint(None, 'tbl_ss_employee', ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_ss_employee', type_='unique')
    op.drop_constraint(None, 'tbl_sociodemographic_data', type_='unique')
    op.drop_constraint(None, 'tbl_health_condition', type_='unique')
    op.add_column('tbl_family_nucleus', sa.Column('ccn_marital_status', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tbl_family_nucleus_ibfk_1', 'tbl_family_nucleus', 'tbl_marital_status', ['ccn_marital_status'], ['ccn_marital_status'])
    op.drop_constraint(None, 'tbl_employment_relationship', type_='unique')
    op.drop_constraint(None, 'tbl_employee', type_='unique')
    op.drop_column('tbl_employee', 'ccn_marital_status')
    op.drop_constraint(None, 'tbl_emergency_contact_details', type_='unique')
    op.drop_constraint(None, 'tbl_demographic_data', type_='unique')
    # ### end Alembic commands ###
