"""20220228_1240

Revision ID: fc9f4d7266be
Revises: 768bd5da76ed
Create Date: 2023-02-28 12:40:40.493182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc9f4d7266be'
down_revision = '768bd5da76ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_employment_relationship', 'manager',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'tbl_employment_relationship', 'tbl_employee', ['manager'], ['ccn_employee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_employment_relationship', type_='foreignkey')
    op.alter_column('tbl_employment_relationship', 'manager',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
